spring:
  application:
    name: zuul-gateway
server:
  port: 5555
  
#传统配置方式
#zuul:
#  routes:
#    eureka-url:
#      path: /eureka/**
#      url: http://localhost:8080/
#    feign-url:
#      path: /feign/**
#      url: http://localhost:7004/

# 面向eureka服务的路由配置
zuul:
  routes:
    eureka-url:
      path: /eureka/**
      serviceId: eureka-client
    feign-url:
      path: /feign/**
      serviceId: feign-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9102/eureka/