spring:
  application:
    name: zuul-gateway
server:
  port: 5555
  
#传统配置方式
#zuul:
#  routes:
#    eureka-url:
#      path: /eureka/**
#      url: http://localhost:8080/
#    feign-url:
#      path: /feign/**
#      url: http://localhost:7004/

# 面向eureka服务的路由配置
zuul:
  #zuul 注册到eureka 时会自动创建映射 通过此参数禁用不需要暴露的服务
#  ignored-patterns:
#    /**
  routes:
    eureka-url:
      path: /eureka/**
      serviceId: eureka-client
    # 更简洁的配置方式
    feign-consumer: /feign/**

    

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9102/eureka/